//
//  SplashViewController.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SplashViewController: UIViewController {

	// MARK: - Property

	var viewModel: SplashViewModel?

	// MARK: - IBOutlet

	@IBOutlet weak var indicatorView: UIActivityIndicatorView!

	// MARK: - View lifecycle

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		navigationController?.setNavigationBarHidden(true, animated: animated)
	}

    override func viewDidLoad() {
        super.viewDidLoad()
		view.backgroundColor = .appBlue
        fetchDatas()
    }

	// MARK: - Private

    private func fetchDatas() {
		indicatorView.isHidden = false
		viewModel?.fetchDatas()
    }
}
