//
//  SplashViewModel.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SplashViewModel: class {
	func fetchDatas()
}

class SplashViewModelImpl {

	// MARK: - Enum

	private enum Constant {
		static let waitTime: Double = 2 // In seconds
	}

	// MARK: - Property

	private var coordinator: SplashCoordinator

	// MARK: - Initialize

	init(coordinator: SplashCoordinator) {
		self.coordinator = coordinator
	}
}

// MARK: - SplashBusinessLogic

extension SplashViewModelImpl: SplashViewModel {

	func fetchDatas() {
		DispatchQueue.main.asyncAfter(deadline: .now() + Constant.waitTime) { [weak self] in
			self?.coordinator.startHome()
		}
	}
}
