//
//  HomeViewController.swift
//  AppWeather
//
//  Created by Johnson-Riche Louis on 26/01/2020.
//  Copyright (c) 2020 Johnson-Richie Louis. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeView: class {
    func update(viewModel: HomeViewModel)
    func updateError(viewModel: HomeErrorViewModel)
}

class HomeViewController: UIViewController {

	// MARK: - Constant

	private enum Constant {
		static let animationDuration = 0.25

		enum Font {
			enum Label {
				static let name = UIFont(name: "HelveticaNeue", size: UIDevice.isIpad ? 30: 24)
				static let description = UIFont(name: "HelveticaNeue", size: UIDevice.isIpad ? 24: 18)
				static let temperature = UIFont(name: "HelveticaNeue", size: UIDevice.isIpad ? 80: 80)
			}
			enum Button {
				static let detail = UIFont(name: "HelveticaNeue", size: 16)
			}
        }
    }

	// MARK: - Property

	var viewModel: HomeViewModel?

	// MARK: - IBOutlet

	@IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var descriptionLabel: UILabel!
    @IBOutlet weak var temperatureLabel: UILabel!
	@IBOutlet weak var indicatorView: UIActivityIndicatorView!
	@IBOutlet weak var detailButton: UIButton!

	// MARK: - View lifecycle

	override func viewDidLoad() {
        super.viewDidLoad()
        fetchContent()
        setupUI()
        setupTableView()
    }

	override func viewWillAppear(_ animated: Bool) {
		super.viewWillAppear(animated)
		navigationController?.setNavigationBarHidden(false, animated: animated)
	}

	// MARK: - IBAction

	@IBAction func didTapDetail(_ sender: Any) {
		viewModel?.didTapDetail()
	}

	// MARK: - Private

	private func fetchContent() {
		indicatorView.isHidden = false
        viewModel?.fetchDatas()
    }

	private func setupUI() {
		view.backgroundColor = .appBlue
        nameLabel.textColor = .appWhite
		nameLabel.font = Constant.Font.Label.name
        nameLabel.alpha = 0

		descriptionLabel.textColor = .appWhite
		descriptionLabel.font = Constant.Font.Label.description
        descriptionLabel.alpha = 0

		temperatureLabel.textColor = .appWhite
		temperatureLabel.font = Constant.Font.Label.temperature
        temperatureLabel.alpha = 0

		tableView.backgroundColor = .clear
        tableView.separatorStyle = .none
        tableView.alpha = 0

		detailButton.backgroundColor = .appWhite
		detailButton.layer.cornerRadius = detailButton.bounds.height / 2
		detailButton.layer.masksToBounds = true
		detailButton.setTitle("home.detail.button".localized(), for: .normal)
		detailButton.setTitleColor(.appBlue, for: .normal)
		detailButton.titleLabel?.font = Constant.Font.Button.detail

		let textAttributes = [NSAttributedString.Key.foregroundColor: UIColor.appBlack]
        navigationController?.navigationBar.titleTextAttributes = textAttributes
		title = "home.title".localized()
    }

	private func setupTableView() {
        tableView.register(HomeTableViewCell.nib, forCellReuseIdentifier: HomeTableViewCell.identifier)
		tableView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: 80, right: 0)
    }
}

// MARK: - HomeDisplayLogic

extension HomeViewController: HomeView {

	func update(viewModel: HomeViewModel) {
        self.viewModel = viewModel
		indicatorView.isHidden = true
        nameLabel.text = viewModel.name
        descriptionLabel.text = viewModel.description
        temperatureLabel.text = viewModel.currentTemperature
		UIView.animate(withDuration: Constant.animationDuration) {
            self.nameLabel.alpha = 1
            self.descriptionLabel.alpha = 1
            self.temperatureLabel.alpha = 1
            self.tableView.alpha = 1
        }
        tableView.reloadData()
    }

	func updateError(viewModel: HomeErrorViewModel) {
		indicatorView.isHidden = true
        let alert = UIAlertController(title: viewModel.title,
                                      message: viewModel.message,
                                      preferredStyle: .alert)
        let action = UIAlertAction(title: viewModel.actionTitle, style: .default) { _ in
            self.dismiss(animated: true, completion: nil)
        }
        alert.addAction(action)
        present(alert, animated: true, completion: nil)
    }
}

// MARK: - UITableViewDataSource

extension HomeViewController: UITableViewDataSource {

	func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return viewModel?.days.count ?? 0
    }

	func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        guard let cell = tableView.dequeueReusableCell(withIdentifier: HomeTableViewCell.identifier,
                                                       for: indexPath) as? HomeTableViewCell,
            let viewModel = viewModel?.days[indexPath.row] else {
                return UITableViewCell()
        }
        let cellViewModel = HomeTableViewCellViewModel(name: viewModel.name,
													   imageUrl: viewModel.imageUrl,
                                                       max: viewModel.max,
                                                       min: viewModel.min)
        cell.configure(viewModel: cellViewModel)
        return cell
    }
}

// MARK: - UITableViewDelegate

extension HomeViewController: UITableViewDelegate {}
